server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance: 
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
      
spring:
  application:
    name: service-hello
